import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  images: {
    unoptimized: true,
  },
  async redirects() {
    return [
      // Core pages
      { source: "/omwoodoo", destination: "/da/showroom", permanent: true },
      { source: "/omproduktionen", destination: "/da/showroom", permanent: true },
      { source: "/udlejning", destination: "/da/udlejning", permanent: true },
      { source: "/galleri", destination: "/da/galleri", permanent: true },
      { source: "/kopi-af-udlejning", destination: "/da/showroom", permanent: true },
      { source: "/blog", destination: "/da/blog", permanent: true },
      { source: "/bordene", destination: "/da/bordet", permanent: true },
      { source: "/da/blog/bordfodboldbord-koebenhavn", destination: "/da/showroom", permanent: true },

      // Shop categories
      { source: "/category/komplette-borde", destination: "/da/bordet", permanent: true },
      { source: "/category/all-products", destination: "/da/bordet", permanent: true },
      { source: "/category/tilbeh%C3%B8r", destination: "/da/tilpas", permanent: true },
      { source: "/category/spiller-figurer", destination: "/da/tilpas", permanent: true },
      { source: "/category/reservedele", destination: "/da/tilpas", permanent: true },

      // Shop products
      { source: "/product-page/spillerfigur-pro-alu-gr%C3%B8n", destination: "/da/tilpas", permanent: true },
      { source: "/product-page/100-udend%C3%B8rs-bordfodbold-1", destination: "/da/bordet", permanent: true },
      { source: "/product-page/spillerfigur-pro-alu-bl%C3%A5", destination: "/da/tilpas", permanent: true },
      { source: "/product-page/stang-u-greb-angreb", destination: "/da/tilpas", permanent: true },
      { source: "/product-page/spillerfigur-pro-alu-sort", destination: "/da/tilpas", permanent: true },
      { source: "/product-page/stang-u-greb-forsvar", destination: "/da/tilpas", permanent: true },
      { source: "/product-page/stang-m-8-kant-greb-midtbane-1", destination: "/da/tilpas", permanent: true },
      { source: "/product-page/spillerfigur-pro-alu-r%C3%B8d", destination: "/da/tilpas", permanent: true },
      { source: "/product-page/stang-u-greb-midtbane", destination: "/da/tilpas", permanent: true },
      { source: "/product-page/spillerfigur-pro-alu", destination: "/da/tilpas", permanent: true },
      { source: "/product-page/pro-bordfodbold-m-stadionlys", destination: "/da/bordet", permanent: true },
      { source: "/product-page/spillerfigur-pro-alu-orange", destination: "/da/tilpas", permanent: true },
      { source: "/product-page/bane-underlag", destination: "/da/tilpas", permanent: true },
      { source: "/product-page/spillerfigur-pro-alu-hvid", destination: "/da/tilpas", permanent: true },
      { source: "/product-page/100-udend%C3%B8rs-logo-bord", destination: "/da/bordet", permanent: true },
      { source: "/product-page/overfladebehandling", destination: "/da/tilpas", permanent: true },
      { source: "/product-page/stang-u-greb-m%C3%A5l", destination: "/da/tilpas", permanent: true },
      { source: "/product-page/gummistop", destination: "/da/tilpas", permanent: true },
      { source: "/product-page/stang-m-8-kant-greb-angreb", destination: "/da/tilpas", permanent: true },
      { source: "/product-page/spillerfigur-pro-alu-lilla", destination: "/da/tilpas", permanent: true },
      { source: "/product-page/100-udend%C3%B8rs-bordfodbold-2", destination: "/da/bordet", permanent: true },
      { source: "/product-page/stang-m-8-kant-greb-midtbane", destination: "/da/tilpas", permanent: true },
      { source: "/product-page/spillerfigur-pro-alu-gul", destination: "/da/tilpas", permanent: true },
      { source: "/product-page/stang-m-8-kant-greb-m%C3%A5l", destination: "/da/tilpas", permanent: true },
      { source: "/product-page/100-udend%C3%B8rs-bordfodbold-pro", destination: "/da/bordet", permanent: true },
      { source: "/product-page/100-udend%C3%B8rs-bordfodbold", destination: "/da/bordet", permanent: true },

      // Blog post migration from Wix (partial — more to follow)
      { source: "/post/rengoering-og-hygiejne-i-faelles-spilzoner-materialer-der-taaler-daglig-drift-inde-og-ude", destination: "/da/blog/rengoering-og-hygiejne-i-faelles-spilzoner", permanent: true },
      { source: "/post/leje-af-bordfodbold-til-events-i-aalborg-dag-weekend-og-firmaleje", destination: "/da/blog/leje-af-bordfodbold-til-events-i-aalborg", permanent: true },
      { source: "/post/udendoers-bordfodbold-til-kommuner-og-byrum-parker-torve-og-aktivitetspladser", destination: "/da/blog/udendoers-bordfodbold-til-kommuner-og-byrum", permanent: true },
      { source: "/post/udendoers-bordfodbold-til-campingpladser-og-feriecentre-robust-aktivitet-til-gaester", destination: "/da/blog/udendoers-bordfodbold-til-campingpladser-og-feriecentre", permanent: true },
      { source: "/post/leje-af-bordfodbold-til-events-i-aarhus-dag-og-weekendleje", destination: "/da/blog/leje-af-bordfodbold-til-events-i-aarhus", permanent: true },
      { source: "/post/business-case-for-udendoers-bordfodbold-saadan-regner-du-effekten-hjem", destination: "/da/blog/business-case-for-udendoers-bordfodbold", permanent: true },
      { source: "/post/leje-af-professionelt-bordfodbold-i-koebenhavn-levering-opsaetning-og-priser", destination: "/da/blog/leje-af-professionelt-bordfodbold-i-koebenhavn", permanent: true },
      { source: "/post/itsf-standarder-forklaret-hvad-goer-et-bordfodboldbord-professionelt", destination: "/da/blog/itsf-standarder-forklaret", permanent: true },
      { source: "/post/dimensioner-og-frizoner-maal-og-afstande-for-bordfodbold-i-offentlige-projekter", destination: "/da/blog/dimensioner-og-frizoner-bordfodbold", permanent: true },
      { source: "/post/lca-og-co2-for-udendoers-aktivitetsudstyr-s%C3%A5dan-vurderer-du-klimaaftryk", destination: "/da/blog/lca-og-co2-for-udendoers-aktivitetsudstyr", permanent: true },
      { source: "/post/dansk-producent-af-rustfrit-udendoers-bordfodbold-direkte-fra-fabrikken", destination: "/da/blog/dansk-producent-af-rustfrit-bordfodbold", permanent: true },
      { source: "/post/case-robust-udendoers-bordfodbold-p%C3%A5-dansk-gymnasium-fra-krav-til-ibrugtagning", destination: "/da/blog/case-robust-udendoers-bordfodbold-paa-gymnasium", permanent: true },
      { source: "/post/professionelle-reservedele-til-bordfodbold-staenger-figurer-og-baneunderlag", destination: "/da/blog/professionelle-reservedele-til-bordfodbold", permanent: true },
      { source: "/post/bordfodbold-til-kontorer-professionelt-udstyr-til-daglig-brug", destination: "/da/blog/bordfodbold-til-kontorer", permanent: true },
      { source: "/post/dansk-producent-vs-importeret-bordfodbold-kvalitet-levering-og-totaloekonomi", destination: "/da/blog/dansk-producent-vs-importeret-bordfodbold", permanent: true },
      { source: "/post/tilgaengelighed-ved-bordfodbold-universelt-design-til-skoler-og-offentlige-rum", destination: "/da/blog/tilgaengelighed-ved-bordfodbold", permanent: true },
      { source: "/post/koeb-vs-leje-vs-leasing-af-professionelt-bordfodbold-hvad-betaler-sig", destination: "/da/blog/koeb-vs-leje-vs-leasing-af-professionelt-bordfodbold", permanent: true },
      { source: "/post/fonde-og-puljer-til-udendoers-aktivitetsudstyr-i-danmark-saadan-soeger-skoler-og-boligforeninger", destination: "/da/blog/fonde-og-puljer-til-udendoers-aktivitetsudstyr", permanent: true },
      { source: "/post/leveringstid-logistik-og-projektforloeb-fra-ordre-til-spilklart-udendoers-bordfodboldbord", destination: "/da/blog/leveringstid-logistik-og-projektforloeb", permanent: true },
      { source: "/post/udendoers-bordfodbold-til-kystnaere-miljoeer-vaelg-korrekt-staal-og-finish", destination: "/da/blog/udendoers-bordfodbold-til-kystnaere-miljoeer", permanent: true },
      { source: "/post/leasing-og-finansiering-af-professionelt-udendoers-bordfodbold", destination: "/da/blog/leasing-og-finansiering-af-bordfodbold", permanent: true },
      { source: "/post/pris-p%C3%A5-rustfrit-udendoers-bordfodbold-hvad-bestemmer-prisen", destination: "/da/blog/pris-paa-rustfrit-udendoers-bordfodbold", permanent: true },
      { source: "/post/kravspecifikation-udendoers-bordfodbold-til-skoler-og-offentlige-miljoeer", destination: "/da/blog/kravspecifikation-udendoers-bordfodbold-til-skoler", permanent: true },
      { source: "/post/rustfrit-staal-vs-pulverlakeret-staal-til-udendoers-bordfodbold", destination: "/da/blog/rustfrit-staal-vs-pulverlakeret-staal", permanent: true },
      { source: "/post/salt-regn-og-frost-s%C3%A5dan-paavirker-dansk-klima-udendors-bordfodbold", destination: "/da/blog/salt-regn-og-frost-dansk-klima-bordfodbold", permanent: true },
      { source: "/post/leje-af-bordfodbold-til-events-i-odense-levering-opsaetning-og-afhentning", destination: "/da/blog/leje-af-bordfodbold-til-events-i-odense", permanent: true },
      { source: "/post/udendoers-bordfodbold-til-efterskoler-og-hoejskoler-priser-levering-og-montering", destination: "/da/blog/udendoers-bordfodbold-til-efterskoler-og-hoejskoler", permanent: true },
      { source: "/post/serviceaftale-for-udendoers-bordfodbold-inspektion-reservedele-og-faste-priser", destination: "/da/blog/serviceaftale-for-udendoers-bordfodbold", permanent: true },
      { source: "/post/fejlfinding-p%C3%A5-bordfodboldbord-9-typiske-problemer-traege-staenger-sloer-stoej-og-hvad-du-goer", destination: "/da/blog/fejlfinding-paa-bordfodboldbord", permanent: true },
      { source: "/post/bordfodbold-til-stadioner-og-events", destination: "/da/blog/bordfodbold-til-stadioner-og-events", permanent: true },
      { source: "/post/faq-udend%C3%B8rs-bordfodbold", destination: "/da/blog/faq-udendoers-bordfodbold", permanent: true },
      { source: "/post/rustfrit-st%C3%A5l-304-vs-316", destination: "/da/blog/rustfrit-staal-304-vs-316", permanent: true },
      { source: "/post/sikre-udend%C3%B8rs-aktivitetsudstyr", destination: "/da/blog/sikker-placering-udendoers-aktivitetsudstyr", permanent: true },
      { source: "/post/planlaegning-af-faellesomraader", destination: "/da/blog/planlaegning-af-faellesomraader", permanent: true },
      { source: "/post/specifikationer-bordfodboldbord", destination: "/da/blog/specifikationer-bordfodboldbord", permanent: true },
      { source: "/post/kob-udendors-bordfodboldbord-til-virksomhed", destination: "/da/blog/koeb-udendoers-bordfodboldbord-til-virksomhed", permanent: true },
      { source: "/post/branding-p%C3%A5-aktivitetsudstyr", destination: "/da/blog/branding-paa-aktivitetsudstyr", permanent: true },
      { source: "/post/vedligeholdele-af-udendors-spil", destination: "/da/blog/vedligeholdelsesguide-udendoers-spil", permanent: true },
      { source: "/post/spil-til-kontor-lounge", destination: "/da/blog/spil-til-kontor-lounge", permanent: true },
      { source: "/post/bordfodbold-vs-bordtennis-vs-pool", destination: "/da/blog/bordfodbold-vs-bordtennis-vs-pool", permanent: true },
      { source: "/post/haervaerksstaerkt-bordfodbold", destination: "/da/blog/haervaerksstaerkt-bordfodbold", permanent: true },
      { source: "/post/baeredygtigt-byrumsinventar", destination: "/da/blog/baeredygtigt-byrumsinventar", permanent: true },
      { source: "/post/installation-bordfodbold-udendors", destination: "/da/blog/installation-bordfodbold-udendoers", permanent: true },
      { source: "/post/bordfodbold-til-hotel", destination: "/da/blog/bordfodbold-til-hotel", permanent: true },
      { source: "/post/tjekliste-krav-til-udend%C3%B8rs-udstyr-i-h%C3%B8jtrafikerede-rum", destination: "/da/blog/tjekliste-krav-udendoers-udstyr-hoejtrafikerede-rum", permanent: true },
      { source: "/post/aktiviteter-skolegaard", destination: "/da/blog/aktiviteter-skolegaard", permanent: true },

      // Blog post migration from Wix (batch 2)
      { source: "/post/leje-af-bordfodbold-til-events-i-herning-messe-firmafest-og-weekendleje", destination: "/da/blog/leje-af-bordfodbold-til-events-i-herning", permanent: true },
      { source: "/post/leje-af-bordfodbold-til-firmafest", destination: "/da/blog/leje-af-bordfodbold-til-firmafest", permanent: true },
      { source: "/post/nyt-eller-brugt-bordfodbold-hvad-boer-du-v%C3%A6lge", destination: "/da/blog/nyt-eller-brugt-bordfodbold", permanent: true },
      { source: "/post/faellesarealer-i-sportshaller-aktiviteter-der-skaber-liv-mellem-traening-og-kamp", destination: "/da/blog/faellesarealer-i-sportshaller", permanent: true },
      { source: "/post/saadan-vaelger-ungdomsklubber-aktiviteter-der-holder-til-hoej-daglig-belastning", destination: "/da/blog/saadan-vaelger-ungdomsklubber-aktiviteter", permanent: true },
      { source: "/post/bordfodbold-som-trivselstiltag-derfor-virker-det-i-skolegaarde-kantiner-og-faellesarealer", destination: "/da/blog/bordfodbold-som-trivselstiltag", permanent: true },
      { source: "/post/fritstaaende-eller-fastgjort-bordfodbold", destination: "/da/blog/fritstaaende-eller-fastgjort-bordfodbold", permanent: true },
      { source: "/post/bordfodbold-til-ungdomsklubber-og-fritidscentre-robust-loesning-til-daglig-brug", destination: "/da/blog/bordfodbold-til-ungdomsklubber-og-fritidscentre", permanent: true },
      { source: "/post/5-tegn-p%C3%A5-et-professionelt-bordfodboldbord", destination: "/da/blog/5-tegn-paa-et-professionelt-bordfodboldbord", permanent: true },
      { source: "/post/indendoers-eller-udendoers-bordfodbold", destination: "/da/blog/indendoers-eller-udendoers-bordfodbold", permanent: true },
      { source: "/post/7-steder-til-udendoers-bordfodbold", destination: "/da/blog/7-steder-til-udendoers-bordfodbold", permanent: true },
      { source: "/post/bordfodbold-til-sportshaller-og-idraetsanlaeg-til-foyer-lounge-og-faellesarealer", destination: "/da/blog/bordfodbold-til-sportshaller-og-idraetsanlaeg", permanent: true },
      { source: "/post/planlaegning-af-faellesomraader", destination: "/da/blog/planlaegning-af-faellesomraader", permanent: true },
      { source: "/post/leje-af-bordfodbold-til-messer", destination: "/da/blog/leje-af-bordfodbold-til-messer", permanent: true },
    ];
  },
};

export default nextConfig;